---
title: "Missing Data Handling on a Historical Voyages of Captive Africans"
author: "Gaurav Sharma"
date: "02/07/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(tidymodels)
library(tidyverse)
```

# Lets load the data
```{r}
tt_data <- tidytuesdayR::tt_load("2020-06-16")

census <- tt_data$census
slave_routes <- tt_data$slave_routes
african_names <- tt_data$african_names
blackpast <- tt_data$blackpast
```

```{r}
skimr::skim(african_names)
```

```{r}
DataExplorer::plot_histogram(african_names)
DataExplorer::plot_missing(african_names)
```

```{r}

african_names %>% 
    filter(year_arrival < 1850) %>% 
    group_by(year_arrival) %>% 
    summarise(mean_age = mean(age, na.rm = T)) %>% 
    ungroup() %>% 
    ggplot(aes(year_arrival, mean_age)) +
    geom_line(size = 2, color = 'cyan3') +
    geom_smooth(method = "lm", size = 2, color = 'orange', alpha = 0.1) +
    scale_y_continuous(limits = c(0,NA))
    
```


```{r}
african_names %>% 
    ggplot(aes(gender, year_arrival)) +
    geom_boxplot(aes(fill = gender), color = "gray")
```


```{r}
african_names %>% 
    ggplot(aes(gender, age)) +
    geom_boxplot(aes(fill = gender), color = "gray")
```


```{r}
library(ggrepel)
african_names %>% 
    group_by(name) %>% 
    summarise(n = n(),
              age = mean(age, na.rm = T),
              year_arrival = median(year_arrival, na.rm = T)) %>% 
    ungroup() %>% 
    filter(n > 30) %>% 
    ggplot(aes(year_arrival, age)) +
        geom_point(aes(size = n), alpha = 0.5) +
    geom_text_repel(aes(label = name), size = 3, color = 'gray60') +
    labs(size = "Number of People")
```


```{r}
liberated_df <- african_names %>% 
    filter(year_arrival < 1850) %>% 
    mutate(gender = case_when(gender == "Boy" ~ "Man",
                              gender == "Girl" ~ "Woman",
                              TRUE ~ gender)) %>% 
    mutate_if(is.character, factor)
```


```{r}
library(naniar)
liberated_df %>% 
    select(gender, age, height) %>% 
    gg_miss_upset()
```


```{r}
skimr::skim(liberated_df)

impute_rec <-
    recipe(year_arrival ~ age + gender + height, data = liberated_df) %>%
    step_meanimpute(height) %>%
    step_knnimpute(all_predictors())

```


```{r}
imputed <- prep(impute_rec) %>%
    juice()
```

```{r}
summary(liberated_df$gender)
summary(imputed$gender)
```

```{r}
summary(liberated_df$age)
summary(imputed$age)
```

# Fit Model
```{r}
fit_lm <- lm(year_arrival ~ age + gender + height, data = imputed)
summary(fit_lm)
tidy(fit_lm)

```

# Thanks